version: '3.2'
services:
  composer:
    image: composer/composer:php7
    command: install
    volumes:
      - .:/app

  example:
    environment:
      - FORWARD_HTTP_PROXY_USERNAME
      - FORWARD_HTTP_PROXY_PASSWORD
      - FORWARD_HTTP_PROXY_HOST
      - REVERSE_HTTP_PROXY_HOST
    build: .
    depends_on:
      - composer
    volumes:
      - .:/app