version: '2.1'
services:
  selenium-firefox:
    image: selenium/standalone-chrome-debug
    expose:
     - 4444
     - 5900
    ports:
     - "4444:4444"
     - "5900:5900"
  main:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
     - selenium-firefox
    links:
     - selenium-firefox